name: Gearcoleco CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update OS
      run: sudo apt-get update -qq
    - name: Install dependencies
      run: sudo apt-get install -y libsdl2-dev libglew-dev
    - name: make
      run: make
      working-directory: platforms/linux
  macos:
    name: macOS
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: brew install sdl2
    - name: make
      run: make dist
      working-directory: platforms/macos
    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: macOS App bundle
        path: platforms/macos/Gearcoleco.app
